version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            echo Hello, world.
            pip3 install pytest
            pytest .

      - run:
          name: Print the Current Time
          command: date