version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            echo Hello, world.
            sudo pip install --upgrade pip
            sudo pip install pytest
      - run:
          name: run pytest
            pytest .
      - run:
          name: Print the Current Time
          command: date